---
- hosts: all
  become: yes
  tasks:
    - name: Set master flag
      set_fact: master=yes
      when: ansible_host == masterIp

    # Set timezone

    - name: Set timezone
      timezone:
        name: "{{ timezone }}"

    # apt update && apt upgrade

    - name: Update and upgrade apt packages
      apt:
        upgrade: yes
        update_cache: yes
        cache_valid_time: 1

    # Setup Docker

    - name: Check if Docker is installed
      command: which docker
      register: whichDocker
      ignore_errors: yes

    # TODO isn't there an ansible module for calling curl?
    - name: Get Docker install script
      command:
        cmd: curl -fsSL get.docker.com -o get-docker.sh
      when: whichDocker.failed == true

    - name: Install Docker
      command:
        cmd: sh get-docker.sh
      when: whichDocker.failed == true

    - name: Start Docker service
      systemd:
        name: docker
        state: started

    # Disable swap
    # TODO supposed to be obsolete - is it?

#    - name: Remove swapfile from /etc/fstab
#      mount:
#        name: "{{ item }}"
#        fstype: swap
#        state: absent
#      with_items:
#        - swap
#        - none
#
#    - name: Disable swap
#      command: swapoff -a

    # Setup Kubernetes

    - name: Add an apt signing key for Kubernetes
      apt_key:
        url: https://packages.cloud.google.com/apt/doc/apt-key.gpg
        state: present

    - name: Adding apt repository for Kubernetes
      apt_repository:
        repo: deb https://apt.kubernetes.io/ kubernetes-xenial main # TODO move dist identifier "xenial" to a config entry
        state: present
        filename: kubernetes.list

    - name: Install Kubernetes binaries
      apt:
        name: "{{ packages }}"
        state: present
        update_cache: yes
      vars:
        packages:
          - kubelet
          - kubeadm
          - kubectl

    - name: Restart kubelet
      service:
        name: kubelet
        daemon_reload: yes
        state: restarted

    # TODO why?
    - name: Reset Kubernetes cluster
      command: kubeadm reset -f

    # TODO not idempotent
    - name: Initialize the Kubernetes cluster using kubeadm
      command: kubeadm init --pod-network-cidr=192.168.0.0/16
      when: master is defined

    - name: Create .kube directory
      become: no
      file:
        path: /home/{{ ansible_user }}/.kube
        state: directory
      when: master is defined

    - name: Copy kubernetes config to home directory
      copy:
        src: /etc/kubernetes/admin.conf
        dest: /home/{{ ansible_user }}/.kube/config
        remote_src: yes
        owner: "{{ ansible_user }}"
      when: master is defined

    # Join Kubernetes nodes

    - name: Generate join command
      command: kubeadm token create --print-join-command
      register: join_command
      when: master is defined

    - name: Copy join command to local file
      become: no
      local_action:
        module: copy
        content: "{{ join_command.stdout_lines[0] }}"
        dest: /tmp/join-command
      when: master is defined

    - name: Copy the join command to server location
      copy: src=/tmp/join-command dest=/tmp/join-command.sh mode=0777
      when: master is not defined

    - name: Join the node to cluster
      command: sh /tmp/join-command.sh
      when: master is not defined

    # Setup CNI

    - name: Install Flannel pod network
      become: false
      command:  kubectl apply -f https://raw.githubusercontent.com/coreos/flannel/master/Documentation/kube-flannel.yml
      when: master is defined
